In [2]:
!pip install pandas

Requirement already satisfied: pandas in d:\study material\python\pandas\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\study material\python\pandas\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('search_logs.csv')

In [5]:
df.head()

,search_id,user_id,search_query,search_date,results_returned,clicked_result_position,device_type,search_duration_seconds,had_typo,used_filters,location_country
0,search_000001,user_09864,classic movies,2024-03-22,20,2.0,Tablet,12.4,False,False,Canada
1,search_000002,user_08038,stand up comedy,2025-11-22,24,4.0,Tablet,63.5,True,False,USA
2,search_000003,user_02009,music documentaries,2024-10-09,86,1.0,Tablet,24.7,True,False,USA
3,search_000004,user_01083,comedy shows,2024-12-14,70,4.0,Mobile,53.7,False,False,USA
4,search_000005,user_04269,movies based on true stories,2025-01-10,48,NaN,Tablet,69.6,True,False,USA

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26500 entries, 0 to 26499
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   search_id                26500 non-null  object
 1   user_id                  26500 non-null  object
 2   search_query             26500 non-null  object
 3   search_date              26500 non-null  object
 4   results_returned         26500 non-null  int64
 5   clicked_result_position  12951 non-null  float64
 6   device_type              26500 non-null  object
 7   search_duration_seconds  25223 non-null  float64
 8   had_typo                 26500 non-null  bool
 9   used_filters             26500 non-null  bool
 10  location_country         26500 non-null  object
dtypes: bool(2), float64(2), int64(1), object(6)
memory usage: 1.9+ MB

In [7]:
df.columns

Index(['search_id', 'user_id', 'search_query', 'search_date',
       'results_returned', 'clicked_result_position', 'device_type',
       'search_duration_seconds', 'had_typo', 'used_filters',
       'location_country'],
      dtype='object')

In [8]:
df.shape

(26500, 11)

In [9]:
df.replace({
    'False': 0, 'True': 1, 'yes': 1, 'No': 0
})

,search_id,user_id,search_query,search_date,results_returned,clicked_result_position,device_type,search_duration_seconds,had_typo,used_filters,location_country
0,search_000001,user_09864,classic movies,2024-03-22,20,2.0,Tablet,12.4,False,False,Canada
1,search_000002,user_08038,stand up comedy,2025-11-22,24,4.0,Tablet,63.5,True,False,USA
2,search_000003,user_02009,music documentaries,2024-10-09,86,1.0,Tablet,24.7,True,False,USA
3,search_000004,user_01083,comedy shows,2024-12-14,70,4.0,Mobile,53.7,False,False,USA
4,search_000005,user_04269,movies based on true stories,2025-01-10,48,NaN,Tablet,69.6,True,False,USA
...,...,...,...,...,...,...,...,...,...,...,...
26495,search_004094,user_02131,stand up comedy,2025-05-09,80,6.0,Smart TV,25.0,True,True,Canada
26496,search_007094,user_07935,thriller series,2024-03-05,36,NaN,Smart TV,15.6,False,True,USA
26497,search_003206,user_05028,classic movies,2024-11-12,18,4.0,Smart TV,24.6,False,False,Canada
26498,search_000206,user_09780,comedy shows,2025-06-04,83,NaN,Laptop,16.1,False,False,USA
26499,search_018032,user_07537,stand up comedy,2024-03-29,9,2.0,Laptop,31.5,False,False,Canada

In [10]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\1842323058.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [11]:
df.dropna(thresh=len(df.columns) - 3, inplace=True)

In [12]:
df.replace(r'^\s*$', pd.NA, regex=True, inplace=True)

In [14]:
df.replace({True: 1, False: 0, 'True': 1, 'False': 0}, inplace=True)

C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_19900\2852048486.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({True: 1, False: 0, 'True': 1, 'False': 0}, inplace=True)

In [15]:
df.to_csv("search_cleaned.csv", index=False)