In [2]:
!pip install pandas numpy matplotlib

Collecting pandas
  Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.3.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.6-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.60.0-cp313-cp313-win_amd64.whl.metadata (113 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-11.3.0-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: six>=1.5 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
Downloading numpy-2.3.3-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   --------- ------------------------------ 3.1/12.8 MB 16.5 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.8 MB 21.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 22.6 MB/s  0:00:00
Using cached matplotlib-3.10.6-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.60.0-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Using cached pillow-11.3.0-cp313-cp313-win_amd64.whl (7.0 MB)
Using cached pyparsing-3.2.5-py3-none-any.whl (113 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib

   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   ------- --------------------------------  2/11 [pyparsing]
   ------- --------------------------------  2/11 [pyparsing]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   ------------------ ---------------------  5/11 [kiwisolver]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   ------------------------- --------------  7/11 [cycler]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [4]:
pd.__version__

'2.3.2'

In [5]:
df = pd.read_csv('each_ball_records.csv')

In [6]:
df.head()

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0

In [7]:
df.columns

Index(['match_no', 'ballnumber', 'inningno', 'over', 'outcome', 'batter',
       'bowler', 'comment', 'score'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17863 entries, 0 to 17862
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   match_no    17863 non-null  int64
 1   ballnumber  17863 non-null  int64
 2   inningno    17863 non-null  int64
 3   over        17863 non-null  float64
 4   outcome     17863 non-null  object
 5   batter      17863 non-null  object
 6   bowler      17863 non-null  object
 7   comment     17863 non-null  object
 8   score       17863 non-null  int64
dtypes: float64(1), int64(4), object(4)
memory usage: 1.2+ MB

In [10]:
type(df["outcome"])

pandas.core.series.Series

In [13]:
new_columns_name = [] 
for i in df.columns:
    new_columns_name.append(i.capitalize())

In [14]:
new_columns_name

['Match_no',
 'Ballnumber',
 'Inningno',
 'Over',
 'Outcome',
 'Batter',
 'Bowler',
 'Comment',
 'Score']

In [15]:
df.columns = new_columns_name
df.head()

,Match_no,Ballnumber,Inningno,Over,Outcome,Batter,Bowler,Comment,Score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.isna().sum()

Match_no      0
Ballnumber    0
Inningno      0
Over          0
Outcome       0
Batter        0
Bowler        0
Comment       0
Score         0
dtype: int64

In [21]:
df.fillna(method='ffill', inplace=True)

C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_7468\3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [22]:
df["Ballnumber"].nunique()

136

In [23]:
df.head(12)

,Match_no,Ballnumber,Inningno,Over,Outcome,Batter,Bowler,Comment,Score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
5,1,6,1,0.6,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
6,1,7,1,1.1,4,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, Four,",4
7,1,8,1,1.2,0,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, no run,",0
8,1,9,1,1.3,4,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, Four,",4
9,1,10,1,1.4,1,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, 1 run,",1
10,1,11,1,1.5,1,Devon Conway,Hardik Pandya,"Hardik Pandya to Devon Conway, 1 run,",1
11,1,12,1,1.6,1,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, 1 run,",1

In [33]:
type(df["Outcome"])

pandas.core.series.Series

In [50]:
# df["Outcome"] = df["Outcome"].replace("1lb", 1).astype(int)

In [ ]:
# df["Outcome"] = pd.to_numeric(df["Outcome"], errors='coerce')

In [51]:
# df["Outcome"] = df["Outcome"].fillna(0).astype(int)

In [52]:
# df.head()

In [48]:
df.drop_duplicates(inplace=True)

In [53]:
df["runs"] = pd.to_numeric(df["outcome"], errors="coerce").fillna(0).astype(int)

KeyError: 'outcome'

In [54]:
df["runs"] = pd.to_numeric(df["outcome"], errors="coerce").fillna(0).astype(int)

KeyError: 'outcome'