In [1]:
!pip install pandas numpy matplotlib

Requirement already satisfied: pandas in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (3.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('each_match_records.csv')

In [4]:
df.head()

,season,date,match_number,match_type,venue,location,team1,team2,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
0,2023,31-03-2023,1,Group,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan
1,2023,01-04-2023,2,Group,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Arshdeep Singh
2,2023,01-04-2023,3,Group,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,AK Chaudhary,NA Patwardhan,M Kuppuraj,DS Manohar,Lucknow Super Giants,50.0,NaN,MA Wood
3,2023,02-04-2023,4,Group,Rajiv Gandhi International Stadium,Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,KN Ananthapadmanabhan,R Pandit,Abhijit Bhattacharya,V Narayan Kutty,Rajasthan Royals,72.0,NaN,JC Buttler
4,2023,02-04-2023,5,Group,M Chinnaswamy Stadium,Bengaluru,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Nitin Menon,Tapan Sharma,A Bengeri,J Srinath,Royal Challengers Bangalore,NaN,8.0,F du Plessis

In [6]:
df.columns

Index(['season', 'date', 'match_number', 'match_type', 'venue', 'location',
       'team1', 'team2', 'toss_won', 'toss_decision', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'winner_runs',
       'winner_wickets', 'man_of_match'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          74 non-null     int64
 1   date            74 non-null     object
 2   match_number    74 non-null     int64
 3   match_type      74 non-null     object
 4   venue           74 non-null     object
 5   location        74 non-null     object
 6   team1           74 non-null     object
 7   team2           74 non-null     object
 8   toss_won        74 non-null     object
 9   toss_decision   74 non-null     object
 10  umpire1         74 non-null     object
 11  umpire2         74 non-null     object
 12  reserve_umpire  74 non-null     object
 13  match_referee   74 non-null     object
 14  winner          74 non-null     object
 15  winner_runs     40 non-null     float64
 16  winner_wickets  33 non-null     float64
 17  man_of_match    73 non-null     object
dtypes: float64(2), int64(2), object(14)
memory usage: 10.5+ KB

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isna().sum()

season             0
date               0
match_number       0
match_type         0
venue              0
location           0
team1              0
team2              0
toss_won           0
toss_decision      0
umpire1            0
umpire2            0
reserve_umpire     0
match_referee      0
winner             0
winner_runs       34
winner_wickets    41
man_of_match       1
dtype: int64

In [12]:
df["man_of_match"].nunique()

51

In [21]:
new_columns_name = [] 
for i in df.columns:
    new_columns_name.append(i.capitalize())

In [22]:
df.head(2)

,season,date,match_number,match_type,venue,location,team1,team2,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
0,2023,31-03-2023,1,Group,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan
1,2023,01-04-2023,2,Group,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Arshdeep Singh

In [23]:
df.columns

Index(['season', 'date', 'match_number', 'match_type', 'venue', 'location',
       'team1', 'team2', 'toss_won', 'toss_decision', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'winner_runs',
       'winner_wickets', 'man_of_match'],
      dtype='object')

In [25]:
df["date"] = pd.to_datetime(df["date"], dayfirst=True)

In [26]:
df.head()

,season,date,match_number,match_type,venue,location,team1,team2,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
0,2023,2023-03-31,1,Group,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan
1,2023,2023-04-01,2,Group,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Arshdeep Singh
2,2023,2023-04-01,3,Group,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,AK Chaudhary,NA Patwardhan,M Kuppuraj,DS Manohar,Lucknow Super Giants,50.0,NaN,MA Wood
3,2023,2023-04-02,4,Group,Rajiv Gandhi International Stadium,Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,KN Ananthapadmanabhan,R Pandit,Abhijit Bhattacharya,V Narayan Kutty,Rajasthan Royals,72.0,NaN,JC Buttler
4,2023,2023-04-02,5,Group,M Chinnaswamy Stadium,Bengaluru,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Nitin Menon,Tapan Sharma,A Bengeri,J Srinath,Royal Challengers Bangalore,NaN,8.0,F du Plessis

In [27]:
new_columns_name = [] 
for i in df.columns:
    new_columns_name.append(i.capitalize())

In [28]:
df.head(2)

,season,date,match_number,match_type,venue,location,team1,team2,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
0,2023,2023-03-31,1,Group,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan
1,2023,2023-04-01,2,Group,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Arshdeep Singh